// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:

         return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8wriMTH2FEVYSrMJ9kQgGF1z3ksPAAs',
    appId: '1:285337494679:ios:1ee6e9024fb639502735d2',
    messagingSenderId: '285337494679',
    projectId: 'quantitysavers',
    storageBucket: 'quantitysavers.appspot.com',
    androidClientId: '285337494679-rp054is62s93l9eihej42nhr6bbbnbp3.apps.googleusercontent.com',
    iosClientId: '285337494679-sv8t93rkjlloqe3oqp02ro3js3mcq83h.apps.googleusercontent.com',
    iosBundleId: 'com.hf.quantitysavers',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjP1l5wUid6pTmbZzT4mRH5Q0SaADzhxs',
    appId: '1:285337494679:android:e638b67cb657b0b12735d2',
    messagingSenderId: '285337494679',
    projectId: 'quantitysavers',
    storageBucket: 'quantitysavers.appspot.com',
  );

}